const fs = require('fs');
const path = require('path');
function w(p, c) { fs.mkdirSync(path.dirname(p), { recursive: true }); fs.writeFileSync(p, c, 'utf8'); console.log('Created:', p); }

w('components/generate/DocumentForm.tsx',
`'use client';
import { useTranslation } from 'react-i18next';
import type { DocumentFormData } from '../../types';

interface Props {
  fields: DocumentFormData;
  step: number;
  templateType: string;
  onChange: (key: keyof DocumentFormData, val: string) => void;
}

export default function DocumentForm({ fields, step, templateType, onChange }: Props) {
  const { t } = useTranslation();
  const isRTI = templateType === 'rti';
  const inp = (key: keyof DocumentFormData, label: string, type = 'text', multi = false) => (
    <div key={key}>
      <label className="label">{label}</label>
      {multi
        ? <textarea className="input-field" value={fields[key] || ''} onChange={e => onChange(key, e.target.value)} rows={3} />
        : <input className="input-field" type={type} value={fields[key] || ''} onChange={e => onChange(key, e.target.value)} />
      }
    </div>
  );

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
      {step === 1 && (<>
        {inp('name', t('generate.name'))}
        {inp('address', t('generate.address'), 'text', true)}
        {inp('phone', t('generate.phone'), 'tel')}
        {inp('date', t('generate.date'), 'date')}
      </>)}
      {step === 2 && (<>
        {isRTI ? (<>
          {inp('authority', t('generate.authority'))}
          {inp('infoRequested', t('generate.info_requested'), 'text', true)}
        </>) : (<>
          {inp('incidentDate', t('generate.incident_date'), 'date')}
          {inp('respondentName', t('generate.respondent_name'))}
          {inp('respondentAddress', t('generate.respondent_address'), 'text', true)}
          {inp('description', t('generate.description'), 'text', true)}
          {inp('amount', t('generate.amount'))}
        </>)}
      </>)}
    </div>
  );
}
`);

w('components/generate/DocumentPreview.tsx',
`'use client';
import { useTranslation } from 'react-i18next';
import type { DocumentFormData } from '../../types';

function makeComplaintText(fields: DocumentFormData, title: string, law: string): string {
  return \`\${title.toUpperCase()}

TO,
\${fields.respondentName || 'The Appropriate Authority'}
\${fields.respondentAddress || ''}

SUBJECT: Complaint / Grievance Application

Respected Sir/Madam,

I, \${fields.name || '[Your Name]'}, residing at \${fields.address || '[Your Address]'}, hereby lodge this formal complaint.

Date of Incident: \${fields.incidentDate || '[Date]'}

Description of Grievance:
\${fields.description || '[Describe the issue in detail]'}

\${fields.amount ? 'Amount Involved: Rs. ' + fields.amount : ''}

I request your urgent intervention and appropriate action under \${law}.

I have attached all relevant documentation in support of this complaint. I request resolution within 30 days as per applicable law.

Yours sincerely,

____________________
\${fields.name || '[Signature]'}
\${fields.address || ''}
Phone: \${fields.phone || ''}
Date: \${fields.date || new Date().toLocaleDateString('en-IN')}

---
This document was generated by NyayaSaathi (nyayasaathi.in).
DISCLAIMER: This is a template. Review before submission. Not legal advice.
\`;
}

function makeRTIText(fields: DocumentFormData): string {
  return \`RTI APPLICATION UNDER RIGHT TO INFORMATION ACT, 2005

TO,
The Public Information Officer
\${fields.authority || '[Public Authority / Department Name]'}

SUBJECT: Application under Section 6(1) of the Right to Information Act, 2005

Respected Public Information Officer,

I, \${fields.name || '[Your Name]'}, a citizen of India, residing at \${fields.address || '[Your Address]'}, wish to obtain the following information under the Right to Information Act, 2005:

INFORMATION REQUESTED:
\${fields.infoRequested || '[Please specify the information you are requesting]'}

I am enclosing the prescribed application fee of Rs. 10/- via [Postal Order / IPO / Online Transfer].

Kindly provide the above information within 30 days as mandated by Section 7(1) of the RTI Act, 2005.

Yours faithfully,

____________________
\${fields.name || '[Your Name]'}
\${fields.address || '[Your Address]'}
Phone: \${fields.phone || ''}
Date: \${fields.date || new Date().toLocaleDateString('en-IN')}

---
This document was generated by NyayaSaathi (nyayasaathi.in).
DISCLAIMER: This is a template. Review before submission. Not legal advice.
\`;
}

interface Props {
  fields: DocumentFormData;
  templateType: string;
  situationTitle: string;
  lawCitation: string;
}

export default function DocumentPreview({ fields, templateType, situationTitle, lawCitation }: Props) {
  const { t } = useTranslation();
  const text = templateType === 'rti' ? makeRTIText(fields) : makeComplaintText(fields, situationTitle, lawCitation);

  return (
    <div style={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
      <h3 style={{ fontSize: 14, fontWeight: 700, color: '#0f172a', marginBottom: 12 }}>{t('generate.preview_title')}</h3>
      <div style={{
        flex: 1, background: 'white', border: '1px solid #e2e8f0', borderRadius: 10,
        padding: '20px 24px', fontFamily: 'Courier New, monospace', fontSize: 12,
        lineHeight: 1.8, color: '#1e293b', overflowY: 'auto', whiteSpace: 'pre-wrap',
        minHeight: 400, position: 'relative',
      }}>
        <div style={{ position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', opacity: 0.04, fontSize: 48, fontWeight: 900, color: '#1a56db', pointerEvents: 'none', userSelect: 'none', transform: 'rotate(-35deg)' }}>
          NyayaSaathi
        </div>
        {text}
      </div>
    </div>
  );
}

export { makeComplaintText, makeRTIText };
`);

console.log('BATCH 6 DONE');
